#!/bin/bash
GREEN='\033[00;32m'
RESTORE='\033[0m'

echo -e "${GREEN}Uploading build${RESTORE}"
rsync -azv build alexcash.com:/home/ec2-user
echo -e "${GREEN}Uploading nginx conf${RESTORE}"
rsync -azv nginx.conf alexcash.com:/home/ec2-user
echo -e "${GREEN}Uploading archive${RESTORE}"
rsync -azv deepfreeze alexcash.com:/home/ec2-user
ssh -t alexcash.com 'sudo /etc/init.d/nginx restart'
